# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'musety' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for musety

  source 'https://github.com/CocoaPods/Specs.git'
	use_frameworks!
	platform :ios, '10.0'
	pod 'MercadoPagoSDK', '~> 4.0'

  target 'musety-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'musetyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'musety-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for musety-tvOS

  

end
